services:
  - type: web
    name: takutail
    env: python
    plan: free
    buildCommand: build.sh
    startCommand: python manage.py runserver
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: takutail.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString

databases:
  - name: my-django-db
    plan: free
    engine: mysql
    version: 8.0
    defaultDatabaseName: mydatabase
    user: myuser
    password: mypassword
    ipAllowList:
      - source: 0.0.0.0/0