services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "cd myproject && poetry install"
    startCommand: "cd myproject && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-database-name
          property: connectionString
