# Generated by Django 5.1 on 2024-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wari',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
