# Generated by Django 5.1 on 2024-08-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generated_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base', models.CharField(max_length=100, null=True)),
                ('base_amount', models.CharField(max_length=100, null=True)),
                ('ingredient1', models.CharField(blank=True, max_length=100, null=True)),
                ('amount1', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('amount2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('amount3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('amount4', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient5', models.CharField(blank=True, max_length=100, null=True)),
                ('amount5', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('ingredient1', models.CharField(max_length=100)),
                ('ingredient2', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient3', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient4', models.CharField(blank=True, max_length=100, null=True)),
                ('top', models.BooleanField(default=False)),
                ('middle', models.BooleanField(default=False)),
                ('bottom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.PositiveIntegerField()),
                ('ingredient_type', models.CharField(choices=[('SAKE', 'Sake'), ('WARI', 'Wari'), ('OTHER', 'Other')], max_length=10)),
                ('amount', models.CharField(max_length=100)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
            ],
        ),
    ]
