# Generated by Django 5.1 on 2024-08-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='amount1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='amount2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='amount3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='amount4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='amount5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='base',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='base_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='generated_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
