# Generated by Django 5.1 on 2024-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userother',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='usersake',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='userwari',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userother',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersake',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwari',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
